platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

install! 'cocoapods', :warn_for_multiple_pod_sources => false

source 'https://github.com/appodeal/CocoaPods.git'
source 'https://cdn.cocoapods.org/'

def appodeal
  pod 'APDAdColonyAdapter', '3.1.3.0-beta.1'
  pod 'BidMachineAdColonyAdapter', '~> 2.1.0.0'
  pod 'APDAdjustAdapter', '3.1.3.0-beta.1'
  pod 'APDAppLovinAdapter', '3.1.3.1-beta.1'
  pod 'APDAppsFlyerAdapter', '3.1.3.1-beta.1'
  pod 'APDBidMachineAdapter', '3.1.3.1-beta.1' # Required
  pod 'BidMachineAmazonAdapter', '~> 2.1.0.0'
  pod 'BidMachineCriteoAdapter', '~> 2.1.0.0'
  pod 'BidMachineMintegralAdapter', '~> 2.1.0.1'
  pod 'BidMachineSmaatoAdapter', '~> 2.1.0.0'
  pod 'BidMachineTapjoyAdapter', '~> 2.1.0.0'
  pod 'BidMachinePangleAdapter', '~> 2.1.0.0'
  pod 'APDFirebaseAdapter', '3.1.3.1-beta.1'
  pod 'APDGoogleAdMobAdapter', '3.1.3.1-beta.1'
  pod 'APDIABAdapter', '3.1.3.0-beta.1' # Required
  pod 'APDIronSourceAdapter', '3.1.3.0-beta.1'
  pod 'APDFacebookAdapter', '3.1.3.1-beta.1'
  pod 'APDMetaAudienceNetworkAdapter', '3.1.3.1-beta.1'
  pod 'BidMachineMetaAudienceAdapter', '~> 2.1.0.0'
  pod 'APDMyTargetAdapter', '3.1.3.1-beta.1'
  pod 'BidMachineMyTargetAdapter', '~> 2.1.0.1'
  pod 'APDStackAnalyticsAdapter', '3.1.3.0-beta.1' # Required
  pod 'APDUnityAdapter', '3.1.3.1-beta.1'
  pod 'APDVungleAdapter', '3.1.3.1-beta.1'
  pod 'BidMachineVungleAdapter', '~> 2.1.0.2'
  pod 'APDYandexAdapter', '3.1.3.0-beta.1'
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  appodeal
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
