platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

install! 'cocoapods', :warn_for_multiple_pod_sources => false

source 'https://cdn.cocoapods.org'
source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/bidon-io/CocoaPods-Specs.git'

def appodeal
    pod 'Appodeal', '4.3.0'
    # Level Play
    pod 'IronSourceAdMobAdapter', '5.10.0.0'
    pod 'IronSourceBidMachineAdapter', '5.7.0.0'
    pod 'IronSourceBigoAdapter', '5.9.0.0'
    pod 'IronSourceFacebookAdapter', '5.3.0.0'
    pod 'IronSourceFyberAdapter', '5.8.0.0'
    pod 'IronSourceInMobiAdapter', '5.7.0.0'
    pod 'IronSourceMintegralAdapter', '5.13.0.0'
    pod 'IronSourceMobileFuseAdapter', '5.0.0.0'
    pod 'IronSourceMolocoAdapter', '5.5.0.0'
    pod 'IronSourceMyTargetAdapter', '5.9.0.0'
    pod 'IronSourceOguryAdapter', '5.0.0.0'
    pod 'IronSourcePangleAdapter', '5.5.0.0'
    pod 'IronSourceSmaatoAdapter', '5.3.0.0'
    pod 'IronSourceUnityAdsAdapter', '5.6.0.0'
    pod 'IronSourceVerveAdapter', '5.1.0.0'
    pod 'IronSourceVungleAdapter', '5.9.0.0'
    pod 'IronSourceYandexAdapter', '5.7.0.0'
    # Bidon
    pod 'BidonAdapterAmazon', '5.5.0.0'
    pod 'BidonAdapterBidMachine', '3.7.1.1'
    pod 'BidonAdapterBigoAds', '5.2.1.0'
    pod 'BidonAdapterChartboost', '9.10.1.0'
    pod 'BidonAdapterDTExchange', '8.4.7.0'
    pod 'BidonAdapterInMobi', '11.3.0.0'
    pod 'BidonAdapterIronSource', '9.4.0.0.0'
    pod 'BidonAdapterMetaAudienceNetwork', '6.21.1.1'
    pod 'BidonAdapterMintegral', '8.1.3.0'
    pod 'BidonAdapterMobileFuse', '1.9.3.0'
    pod 'BidonAdapterMoloco', '4.3.0.0'
    pod 'BidonAdapterMyTarget', '5.43.0.0'
    pod 'BidonAdapterStartIo', '4.11.0.0'
    pod 'BidonAdapterTaurusX', '1.9.2.0'
    pod 'BidonAdapterUnityAds', '4.17.0.0'
    pod 'BidonAdapterVungle', '7.7.3.0'
    pod 'BidonAdapterYandex', '7.18.4.0'
    pod 'BidonAdapterZmaticoo', '2.2.0.0'
    # Appodeal
    pod 'AppodealAdjustAdapter', '5.7.0.1'
    pod 'AppodealAmazonAdapter', '5.5.0.0'
    pod 'AppodealAppLovinAdapter', '13.6.4.0'
    pod 'AppodealAppLovinMAXAdapter', '13.6.4.2'
    pod 'AppodealAppsFlyerAdapter', '6.18.0.2'
    pod 'AppodealBidMachineAdapter', '3.7.1.0'
    pod 'AppodealBidonAdapter', '0.15.0.0'
    pod 'AppodealBigoAdsAdapter', '5.2.1.0'
    pod 'AppodealDTExchangeAdapter', '8.4.7.0'
    pod 'AppodealFacebookAdapter', '18.0.3.0'
    pod 'AppodealFirebaseAdapter', '12.15.0.1'
    pod 'AppodealGoogleAdMobAdapter', '13.5.0.0'
    pod 'AppodealIABAdapter', '3.5.2.0'
    pod 'AppodealInMobiAdapter', '11.3.0.0'
    pod 'AppodealIronSourceAdapter', '9.4.0.0.0'
    pod 'AppodealLevelPlayAdapter', '9.4.0.0.0'
    pod 'AppodealMetaAudienceNetworkAdapter', '6.21.1.0'
    pod 'AppodealMintegralAdapter', '8.1.3.0'
    pod 'AppodealMyTargetAdapter', '5.43.0.0'
    pod 'AppodealSentryAdapter', '8.57.2.1'
    pod 'AppodealUnityAdapter', '4.17.0.0'
    pod 'AppodealVungleAdapter', '7.7.3.0'
    pod 'AppodealYandexAdapter', '7.18.4.1'
    # AppLovin MAX
    pod 'AppLovinMediationAmazonAdMarketplaceAdapter', '5.5.0.0'
    pod 'AppLovinMediationBidMachineAdapter', '3.7.1.0.0'
    pod 'AppLovinMediationBigoAdsAdapter', '5.2.1.0'
    pod 'AppLovinMediationByteDanceAdapter', '7.7.0.7.0'
    pod 'AppLovinMediationChartboostAdapter', '9.10.1.0'
    pod 'AppLovinMediationFacebookAdapter', '6.21.1.0'
    pod 'AppLovinMediationFyberAdapter', '8.4.7.0'
    pod 'AppLovinMediationGoogleAdManagerAdapter', '13.5.0.0'
    pod 'AppLovinMediationGoogleAdapter', '13.5.0.0'
    pod 'AppLovinMediationInMobiAdapter', '11.3.0.1'
    pod 'AppLovinMediationIronSourceAdapter', '9.4.0.0.0'
    pod 'AppLovinMediationMintegralAdapter', '8.1.3.0.0'
    pod 'AppLovinMediationMobileFuseAdapter', '1.9.3.0'
    pod 'AppLovinMediationMolocoAdapter', '4.3.0.0'
    pod 'AppLovinMediationOguryPresageAdapter', '5.1.1.0'
    pod 'AppLovinMediationPubMaticAdapter', '4.10.0.0'
    pod 'AppLovinMediationSmaatoAdapter', '23.2.0.0'
    pod 'AppLovinMediationUnityAdsAdapter', '4.17.0.0'
    pod 'AppLovinMediationVerveAdapter', '3.7.0.0'
    pod 'AppLovinMediationVungleAdapter', '7.7.3.0'
    pod 'AppLovinMediationYandexAdapter', '7.18.4.0'
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  appodeal

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
